### ISSUE TITLE
identity?

### ISSUE THREAD

**Issue by dwhitney** [bbarker/purescript-either-extra#1]
This looks useful, and I will totally use it. One minor thing I saw in the source - do you need that `identity` function? 

https://github.com/bbarker/purescript-either-extra/blob/main/src/Data/Either/Extra.purs#L10

It's in `Control.Category`

https://pursuit.purescript.org/packages/purescript-prelude/4.1.1/docs/Control.Category#v:identity

**Comment by bbarker** [comment]
I know about it, though it seemed like that would incur an extra dependency; currently, the only dependency is purescript-either. The use case I had in mind was to make this as minimal as possible: for people using a custom prelude, for instance, they may not want to depend on prelude. Though unlike Haskell, I have to admit I'm not even sure if anyone does that in PureScript (though I think it is possible). So I'm certainly open to the possibility in using it, but since it can essentially be defined as a lambda `(\x -> x)`, it isn't a lot of code to worry about, I think.

I have to warn though that this is probably not a highly performance solution, though I've not benchmarked it.

**Comment by bbarker** [comment]
> So I'm certainly open to the possibility of using it, but since it can essentially be defined as a lambda `(\x -> x)`, it isn't a lot of code to worry about, I think.

On the other hand, if every dependency takes this approach, it could add up slightly, though that seems unlikely.

**Comment by dwhitney** [comment]
Hmm - I assumed `identity` would be included in `either`'s dependencies. I don't really think this is important. I just thought I'd bring it to your attention. I assume the function will be removed from any bundle operations I employ. I'll close the issue.

**Comment by bbarker** [comment]
You are right; somehow I thought purescript-either had no dependencies, but it actually depends on prelude (and others). I'll try to get this updated soon.

**Comment by bbarker** [comment]
Fixed in 50ed9ee94328b58a38746ccfb89b26cb5592e297 and in new release 0.0.4
